// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBG2Z_tv6YrrjzpP6wRb2zlLLRXASkb5pQ',
    appId: '1:882797649489:web:9417d97415f1f165b66270',
    messagingSenderId: '882797649489',
    projectId: 'budget-app-82983',
    authDomain: 'budget-app-82983.firebaseapp.com',
    storageBucket: 'budget-app-82983.appspot.com',
    measurementId: 'G-TLWVRJ1HWG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyACOHjulkQT3kDRS6mwTzV4qxg3CYA-mYU',
    appId: '1:882797649489:android:be9345df36dd54ecb66270',
    messagingSenderId: '882797649489',
    projectId: 'budget-app-82983',
    storageBucket: 'budget-app-82983.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDNjPdDALS4WHqBOBHbuUCLAgePu6kOwTg',
    appId: '1:882797649489:ios:8bd5b81e16a54db3b66270',
    messagingSenderId: '882797649489',
    projectId: 'budget-app-82983',
    storageBucket: 'budget-app-82983.appspot.com',
    iosClientId: '882797649489-4i2hjavd1q7ivfh8ljr6ca30l9art3op.apps.googleusercontent.com',
    iosBundleId: 'com.example.newBudgetApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDNjPdDALS4WHqBOBHbuUCLAgePu6kOwTg',
    appId: '1:882797649489:ios:8bd5b81e16a54db3b66270',
    messagingSenderId: '882797649489',
    projectId: 'budget-app-82983',
    storageBucket: 'budget-app-82983.appspot.com',
    iosClientId: '882797649489-4i2hjavd1q7ivfh8ljr6ca30l9art3op.apps.googleusercontent.com',
    iosBundleId: 'com.example.newBudgetApp',
  );
}
